name: Matheus Lubarino
description: Um  blog sobre o que ando apredendo por ai
meta_description: "mean, programação,java,backend,back-end,frontend,front-end,java,angular"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://lubarino.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Matheus Lubarino'
